// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz4ayHZDaTPBXrAk0nU04VKDCWIQ928DE',
    appId: '1:995697446433:web:02690b8fa39a5757aa1d60',
    messagingSenderId: '995697446433',
    projectId: 'aloudeh-220e7',
    authDomain: 'aloudeh-220e7.firebaseapp.com',
    storageBucket: 'aloudeh-220e7.appspot.com',
    measurementId: 'G-6V7JH0L43D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLURIBURy9xiWIFKXsO_FQeybdotpzukc',
    appId: '1:995697446433:android:ee8d46c4fb6cd94eaa1d60',
    messagingSenderId: '995697446433',
    projectId: 'aloudeh-220e7',
    storageBucket: 'aloudeh-220e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAADBpmp20QNvRcQrl0wMhNiqF8XHWOkrw',
    appId: '1:995697446433:ios:2deb4a2ea653534eaa1d60',
    messagingSenderId: '995697446433',
    projectId: 'aloudeh-220e7',
    storageBucket: 'aloudeh-220e7.appspot.com',
    iosBundleId: 'com.example.aloudehCompany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAADBpmp20QNvRcQrl0wMhNiqF8XHWOkrw',
    appId: '1:995697446433:ios:2deb4a2ea653534eaa1d60',
    messagingSenderId: '995697446433',
    projectId: 'aloudeh-220e7',
    storageBucket: 'aloudeh-220e7.appspot.com',
    iosBundleId: 'com.example.aloudehCompany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz4ayHZDaTPBXrAk0nU04VKDCWIQ928DE',
    appId: '1:995697446433:web:782ff5557dd99c6aaa1d60',
    messagingSenderId: '995697446433',
    projectId: 'aloudeh-220e7',
    authDomain: 'aloudeh-220e7.firebaseapp.com',
    storageBucket: 'aloudeh-220e7.appspot.com',
    measurementId: 'G-98GT9EMQRD',
  );

}